import { useEffect, useState } from "react";
import {
  BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
} from "recharts";
import { Button, Card, StatCard, Table, Loader } from "../../components";
import {
  getReportsSummary,
  getCrimeDistribution,
  getForceStrength,
  getActivityLog,
  getReportEngineSections,
} from "../../services/reports";
import "./Reports.css";

export function ReportsPage() {
  const [loading, setLoading] = useState(true);
  const [summary, setSummary] = useState(null);
  const [crimeData, setCrimeData] = useState([]);
  const [forceData, setForceData] = useState([]);
  const [activityLog, setActivityLog] = useState([]);

  useEffect(() => {
    let cancelled = false;
    Promise.all([getReportsSummary(), getCrimeDistribution(), getForceStrength(), getActivityLog()])
      .then(([summaryRes, crimeRes, forceRes, activityRes]) => {
        if (cancelled) return;
        setSummary(summaryRes);
        setCrimeData(crimeRes);
        setForceData(forceRes);
        setActivityLog(activityRes);
      })
      .catch((err) => console.error("Failed to load reports:", err))
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (loading) return <Loader label="Loading reports…" />;

  const sections = getReportEngineSections();

  const logColumns = [
    { key: "reportTitle", label: "Report Title" },
    { key: "type", label: "Type" },
    { key: "generatedBy", label: "Generated by" },
    { key: "date", label: "Date" },
    { key: "status", label: "Status" },
  ];

  return (
    <div className="reports-layout">
      <aside className="reports-sidebar">
        <h3 style={{ marginBottom: 16 }}>Report Engine</h3>
        {sections.map((section) => (
          <div key={section.group} className="reports-sidebar-group">
            <h4>{section.group}</h4>
            <ul>
              {section.items.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </div>
        ))}
      </aside>

      <div>
        <div className="reports-header">
          <div>
            <h1>Reports & Analytics Dashboard</h1>
            <p className="reports-subtitle">Officer station performance metrics and administrative documentation</p>
          </div>
          <div style={{ display: "flex", gap: 8 }}>
            <Button variant="outline">Last 30 Days</Button>
            <Button variant="outline">Print View</Button>
          </div>
        </div>

        <div className="stat-grid" style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 16 }}>
          <StatCard label="Duty Summary" value={`${summary?.dutyCompliancePercent ?? 0}%`} caption={summary?.dutyComplianceCaption} />
          <StatCard label="Leave Statistics" value={`${summary?.leaveStatisticsDays ?? 0} Days`} caption={summary?.leaveStatisticsCaption} />
          <StatCard label="Inventory Movements" value={`${summary?.inventoryMovements ?? 0} Items`} caption={summary?.inventoryMovementsCaption} />
        </div>

        <div className="reports-charts-grid">
          <Card variant="panel" className="chart-card">
            <h4>Crime Incidence Distribution</h4>
            <ResponsiveContainer width="100%" height={220}>
              <BarChart data={crimeData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="category" fontSize={12} />
                <YAxis fontSize={12} />
                <Tooltip />
                <Bar dataKey="count" fill="var(--color-primary)" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </Card>

          <Card variant="panel" className="chart-card">
            <h4>Weekly Force Strength</h4>
            <ResponsiveContainer width="100%" height={220}>
              <LineChart data={forceData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="date" fontSize={12} />
                <YAxis fontSize={12} />
                <Tooltip />
                <Line type="monotone" dataKey="activeDuty" stroke="var(--color-success)" name="Active Duty" />
                <Line type="monotone" dataKey="onLeave" stroke="var(--color-danger)" name="On Leave" />
              </LineChart>
            </ResponsiveContainer>
          </Card>
        </div>

        <Card variant="panel">
          <h4 style={{ marginBottom: 4 }}>Recent Activity Logs</h4>
          <p style={{ fontSize: 13, color: "var(--color-text-muted)", marginBottom: 16 }}>
            Official PDF/CSV reports ready for download
          </p>
          <Table columns={logColumns} data={activityLog} emptyMessage="No reports generated yet" />
        </Card>
      </div>
    </div>
  );
}