
export const navItemsByRole = {
  admin: [
    { key: "dashboard", label: "Dashboard", path: "/dashboard" },
    { key: "personnel", label: "Personnel & User Management", path: "/personnel" },
    { key: "leave", label: "Leave Requests", path: "/leave" },
    { key: "complaints", label: "Complaints registry", path: "/complaints" },
    { key: "reports", label: "Reports", path: "/reports" },
    { key: "audit-log", label: "Activity Log", path: "/audit-log" },
    { key: "notifications", label: "Notifications", path: "/notifications" },
    { key: "settings", label: "Settings", path: "/settings" },
  ],
  oic: [
    { key: "dashboard", label: "Dashboard", path: "/dashboard" },
    { key: "duty-roster", label: "Duty Roster", path: "/duty-roster" },
    { key: "leave", label: "Leave Requests", path: "/leave" },
    { key: "complaints", label: "Complaints registry", path: "/complaints" },
    { key: "inventory", label: "Inventory", path: "/inventory" },
    { key: "reports", label: "Reports", path: "/reports" },
    { key: "notifications", label: "Notifications", path: "/notifications" },
    { key: "settings", label: "Settings", path: "/settings" },
  ],
  duty_officer: [
    { key: "dashboard", label: "Dashboard", path: "/dashboard" },
    { key: "duty-roster", label: "Duty Roster", path: "/duty-roster" },
    //{ key: "inventory", label: "Inventory", path: "/inventory" },
    { key: "weapon-management", label: "My Weapons", path: "/weapon-management" },
    { key: "leave", label: "Leave Requests", path: "/leave" },
    { key: "complaints", label: "Complaints registry", path: "/complaints" },
    { key: "reports", label: "Reports", path: "/reports" },
    { key: "notifications", label: "Notifications", path: "/notifications" },
    { key: "settings", label: "Settings", path: "/settings" },
  ],
  inventory_officer: [
    { key: "dashboard", label: "Dashboard", path: "/dashboard" },
    { key: "inventory", label: "Inventory", path: "/inventory" },
    { key: "weapon-management", label: "My Weapons", path: "/weapon-management" },
    { key: "leave", label: "Leave Requests", path: "/leave" },
    { key: "complaints", label: "Complaints registry", path: "/complaints" },
    { key: "reports", label: "Reports", path: "/reports" },
    { key: "notifications", label: "Notifications", path: "/notifications" },
    { key: "settings", label: "Settings", path: "/settings" },
  ],
  officer: [
    { key: "dashboard", label: "Dashboard", path: "/dashboard" },
    { key: "weapon-management", label: "My Weapons", path: "/weapon-management" },
    { key: "leave", label: "Leave Requests", path: "/leave" },
    { key: "complaints", label: "Complaints registry", path: "/complaints" },
    { key: "notifications", label: "Notifications", path: "/notifications" },
    { key: "settings", label: "Settings", path: "/settings" },
  ],
};